# Generated by Django 4.2.7 on 2023-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='uploads'),
        ),
    ]
