# Generated by Django 4.2.7 on 2023-12-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментари'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='com_post',
            new_name='post',
        ),
    ]
