# Generated by Django 4.2.7 on 2023-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, verbose_name='Login')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
            ],
        ),
    ]
