# Generated by Django 4.2.7 on 2023-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tocontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, verbose_name='Login')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('poster', models.URLField(default='https://i.pinimg.com/564x/92/c5/11/92c511eb998b41b3d6c78fc9522f5927.jpg', verbose_name='Poster')),
            ],
        ),
    ]
