# Generated by Django 4.2.7 on 2023-12-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_login_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login',
            field=models.CharField(default='login', max_length=10, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=10, verbose_name='User'),
        ),
    ]
