# Generated by Django 4.2.7 on 2023-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_login_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='login@mail.com', max_length=30, verbose_name='Email'),
        ),
    ]
